### PR TITLE
Added regression_test flow and 3 extension packages as sources

### PR DESCRIPTION
**Pull request by beAGoodQE**
# Changes
- Added cci flows and sources to assist in QE regression testing

### CODE REVIEW

**Comment by beAGoodQE** [comment]
Do not merge until merge freeze ends on 12/12.

@jstvz I added the code you asked me to.  I did remove the "install_prod_with_abacus" because it threw an error and I think that's already handled by the regression_org flow.  I also updated the flow to call the managed version of the regression tests.

**Comment by annejackson** [comment]
IS merging blocked until this is merged https://github.com/SalesforceFoundation/gem/pull/253
@beAGoodQE  do you know? cc: @jstvz

**Comment by jstvz** [comment]
Waiting on #258.

**Comment by annejackson** [comment]
@beAGoodQE  was this for adding your automated data/testing flows?cc: @markross-sfdo  on release notes.

**Comment by markross-sfdo** [comment]
@annejackson I don't think this one will have release notes, since it's dedicated to cci flows. Is there something I'm missing?

**Comment by annejackson** [comment]
I don't think so either.  You want to edit the changes part and put it above?

**Comment by markross-sfdo** [comment]
Done!

**Pull request merged**
