### PR TITLE
Add a Recurring Donation Tab and Quick Action

### PR DESCRIPTION
**Pull request by grivero**
# Critical Changes

# Changes
**lurch: attach W-038013
Add recurring donation tab to gem app
Add recurring donation related list to Contact layout to match NPSP
Add new recurring donation quick action in Contact layout to match NPSP

# Issues Closed

# New Metadata
- reference to Recurring Donations tab in GEM app
- reference for RecurringDonation related list inside Contact Gem layout

# Deleted Metadata

# Testing Notes
- recurring donation tab is part of "Gift Entry Manager" app
- recurring donations is part of the Contact's related lists. Should be located right after Opportunities
- Contact layout has a quick action to enter New Recurring Donations

### CODE REVIEW

**Comment by grivero** [comment]
**lurch: attach W-038013

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HpcmQAC" target="_blank">W-038013</a>

**Comment by annejackson** [comment]
@vmartinov-sforg  Ben has already reviewed this one, do you want to as well? Otherwise I will move to ready for qa.

**Comment by vmartinov-sforg** [comment]
@ameyersalesforce Do we want to keep this pull request / branch in the GEM repo?

**Comment by vmartinov-sforg** [comment]
Closing stale requests.

**Pull request closed without merging**
