### PR TITLE
Adding Apex class access needed for SGE to our Profile and Perm Set

### PR DESCRIPTION
**Pull request by lparrott**
- This change is only for our testing purposes, so I don't think it requires any change text.

# Critical Changes

# Changes

# Issues Closed

# New Metadata

# Deleted Metadata

# Testing Notes

- Run the dev_org or qa_org flow.
- Login as Gary Gift Officer.
- Ensure that the Single Gift Entry form can be filled out and saves correctly.
- Also check that "read" access to NPSP Relationships and Affiliations has been removed (we've already tested that auto-soft credits work without this access)

### CODE REVIEW

**Comment by lparrott** [comment]
**lurch: attach W-036031

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001CAleQAG" target="_blank">W-036031</a>

**Comment by bdvorachek** [comment]
Looks good in a pre_release config. Form works as expected, and I was not able to access npsp affiliations or or relationships either.

We'll want to re-check as a managed package when we've merged to master.

@lparrott clear for merge?

**Comment by lparrott** [comment]
@bdvorachek Clear for merge (after my last commit)! This will fix our installer issue as well.

**Pull request merged**
