### PR TITLE
Removing reference to Abacus Storage Levels

### PR DESCRIPTION
**Pull request by lparrott**
- Removing references to Abacus Storage Levels, since that field was recently removed.

# Critical Changes

# Changes

# Issues Closed

# New Metadata

# Deleted Metadata

# Testing Notes

### CODE REVIEW

**Comment by lparrott** [comment]
We have a few more changes to make based on some Installer updates, let's hold off on merging this one!

**Comment by annejackson** [comment]
@lparrott what's a good way to test this since it will be removed? cc: @beAGoodQE  as well if he has any ideas.

**Comment by jstvz** [comment]
> @lparrott what's a good way to test this since it will be removed? cc: @beAGoodQE as well if he has any ideas.

@annejackson: `cci flow run regression_org` will include the modified flow. Alternatively, `cci flow run dependencies` followed by `cci task run deploy_abacus_settings` should also work and is probably faster.

**Comment by annejackson** [comment]
> > @lparrott what's a good way to test this since it will be removed? cc: @beAGoodQE as well if he has any ideas.
> 
> @annejackson: `cci flow run regression_org` will include the modified flow. Alternatively, `cci flow run install_prod_with_abacus` followed by `cci task run deploy_abacus_settings` should also work and is probably faster.

And I can run the regression_org flow tied to this feature branch to test  before merge correct, @jstvz ?

**Comment by jstvz** [comment]
> And I can run the regression_org flow tied to this feature branch to test before merge correct, @jstvz ?

Yes, @annejackson

**Comment by annejackson** [comment]
The settings has been removed, merging PR.

**Pull request merged**
