### PR TITLE
[L10n] GEM es_MX add + es bug fixes

### PR DESCRIPTION
**Pull request by GloryChoe**

### CODE REVIEW

**Comment by vmartinov-sforg** [comment]
@GloryChoe  Would it be possible to name the localization  branches feature/<branch-name> from now on. That way it would get automatic updates from master.

**Comment by GloryChoe** [comment]
@vmartinov-sforg I can absolutely do that. Do you want me to create a new PR and close this one?

**Comment by vmartinov-sforg** [comment]
That would be great. Thank you.

**Comment by GloryChoe** [comment]
Created a new pr #270 with new branch name

**Pull request closed without merging**
